### ISSUE TITLE
Assertion error: torchaaudio resample_waveform related

### ISSUE THREAD

**Issue by raikarsagar** [rishikksh20/VocGAN#11]
I am facing assertion error and the log is as follows: 

Traceback (most recent call last):
  File "/home/stuart/sagar/speech_analysis_synth/VocGAN/utils/train.py", line 98, in train
    disc_real, disc_real_multiscale = model_d(audioG, melG)
  File "/home/stuart/sagar/speech_analysis_synth/VocGAN/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stuart/sagar/speech_analysis_synth/VocGAN/model/hierarchical_discriminator.py", line 30, in forward
    x_ = down_(x)
  File "/home/stuart/sagar/speech_analysis_synth/VocGAN/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stuart/sagar/speech_analysis_synth/VocGAN/venv/lib/python3.6/site-packages/torchaudio/transforms.py", line 382, in forward
    return kaldi.resample_waveform(waveform, self.orig_freq, self.new_freq)
  File "/home/stuart/sagar/speech_analysis_synth/VocGAN/venv/lib/python3.6/site-packages/torchaudio/compliance/kaldi.py", line 802, in resample_waveform
    assert waveform.dim() == 2
AssertionError

Any wayouts from this issue will be helpful.
Thanks
Sagar

**Comment by rishikksh20** [comment]
your audio should be single channel, check weather you pass single or dual channel.

**Comment by raikarsagar** [comment]
The files are fine because I was able to train with master branch. The issue persists with baseline branch.

**Comment by rishikksh20** [comment]
don't use that branch, that branch no more maintained.
