### ISSUE TITLE
KeyError: '__getstate__'

### ISSUE THREAD

**Issue by c1a1o1** [rishikksh20/VocGAN#16]
F:\ProgramData\Anaconda3\python.exe F:/work/VocGAN-master/trainer.py
F:\ProgramData\Anaconda3\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
F:\ProgramData\Anaconda3\lib\site-packages\torchaudio\backend\utils.py:64: UserWarning: The interface of "soundfile" backend is planned to change in 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False` before setting the backend to "soundfile". Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  'The interface of "soundfile" backend is planned to change in 0.8.0 to '
Generator : 

Trainable Parameters: 4.714M
Discriminator : 

Trainable Parameters: 4.355M
2020-12-15 16:11:56,529 - INFO - Starting new training run.
Validation loop:   0%|          | 0/36 [00:00<?, ?it/s]F:\ProgramData\Anaconda3\lib\site-packages\torch\functional.py:516: UserWarning: stft will require the return_complex parameter be explicitly  specified in a future PyTorch release. Use return_complex=False  to preserve the current behavior or return_complex=True to return  a complex output. (Triggered internally at  ..\aten\src\ATen\native\SpectralOps.cpp:653.)
  normalized, onesided, return_complex)
F:\ProgramData\Anaconda3\lib\site-packages\torch\functional.py:516: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  ..\aten\src\ATen\native\SpectralOps.cpp:590.)
  normalized, onesided, return_complex)
g 8.2491 d 2.8965 ad 0.9612| step 0: 100%|██████████| 36/36 [00:05<00:00,  6.67it/s]
Loading train data:   0%|          | 0/40 [00:00<?, ?it/s]
2020-12-15 16:12:04,076 - INFO - Exiting due to exception: '__getstate__'
Traceback (most recent call last):
  File "F:\work\VocGAN-master\utils\train.py", line 81, in train
    (melD, audioD) in loader:
  File "F:\ProgramData\Anaconda3\lib\site-packages\tqdm\std.py", line 1127, in __iter__
    for obj in iterable:
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
KeyError: '__getstate__'

**Comment by mumusanren** [comment]
Have you solved this problem yet please? I am having the same problem as you.
